### ISSUE TITLE
System.IO.DirectoryNotFoundException问题

### ISSUE THREAD

**Issue by rgsad4** [HolographicHat/YaeAchievement#31]
运行软件后，显示如下：

----------------------------------------------------
YaeAchievement - 原神成就导出工具 (2.1)
https://github.com/HolographicHat/YaeAchievement
----------------------------------------------------
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\ProgramData\yae.dll'.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at YaeAchievement.Utils.StartAndWaitResult(String exePath, Func`2 onReceive)
   at Program.<Main>$(String[] args)
正在上报错误信息...
按任意键退出

由于其中出现“C:\ProgramData\yae.dll”，猜测是因为我的系统盘的盘符并不是C，且电脑中也没有盘符为C的盘。

**Comment by rgsad4** [comment]
解决了，插个U盘，盘符改成C，并在根目录新建ProgramData文件夹即可
